-- =============================================================================
--  01-schema.sql — schema dùng xuyên suốt giáo trình
-- =============================================================================
--  Mô hình một hệ thống thương mại điện tử rút gọn. Schema này cố tình được giữ
--  ở mức tối thiểu về index: chỉ có PRIMARY KEY và UNIQUE constraint.
--
--  KHÔNG có index nào trên foreign key column (orders.user_id, order_items.order_id,
--  order_items.product_id, payments.order_id). Đây là chủ ý:
--    - Phần 05 và Phần 06 sẽ tự tay thêm từng index và đo lại,
--      thay vì nhận sẵn một schema đã tối ưu và không hiểu vì sao nó tối ưu.
--    - Phần 08 cần trạng thái "thiếu index trên FK" để tái hiện lock contention
--      khi xóa row ở bảng cha.
-- =============================================================================

DROP TABLE IF EXISTS payments, order_items, orders, products, users, categories CASCADE;

CREATE TABLE categories (
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    parent_id   int REFERENCES categories(id)
);

CREATE TABLE users (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        text        NOT NULL UNIQUE,
    full_name    text        NOT NULL,
    country_code char(2)     NOT NULL,
    status       text        NOT NULL DEFAULT 'active',
    created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE products (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         text          NOT NULL UNIQUE,
    name        text          NOT NULL,
    category_id int           NOT NULL REFERENCES categories(id),
    price       numeric(12,2) NOT NULL,
    stock       int           NOT NULL DEFAULT 0,
    created_at  timestamptz   NOT NULL DEFAULT now()
);

CREATE TABLE orders (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      bigint        NOT NULL REFERENCES users(id),
    status       text          NOT NULL,
    total_amount numeric(12,2) NOT NULL DEFAULT 0,
    created_at   timestamptz   NOT NULL
);

CREATE TABLE order_items (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   bigint        NOT NULL REFERENCES orders(id),
    product_id bigint        NOT NULL REFERENCES products(id),
    quantity   int           NOT NULL,
    unit_price numeric(12,2) NOT NULL
);

CREATE TABLE payments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   bigint        NOT NULL REFERENCES orders(id),
    method     text          NOT NULL,
    amount     numeric(12,2) NOT NULL,
    status     text          NOT NULL,
    created_at timestamptz   NOT NULL
);
